DROP TABLE IF EXISTS CUSTOMER cascade;
DROP TABLE IF EXISTS TRANSACTIONS cascade;

CREATE TABLE CUSTOMER
(CUSTOMER_ID INTEGER NOT NULL,
 NAME VARCHAR(25));

CREATE TABLE TRANSACTIONS
(ID INTEGER NOT NULL,
 AMOUNT INTEGER NOT NULL,
 CUSTOMER_ID INTEGER NOT NULL,
 DATE DATE);